---
# Variable variables
- name: Include OS-default variables
  include_vars: default.yml

- name: Include OS-specific variables.
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "{{ansible_distribution}}-{{ansible_distribution_release}}.yml"
      - "{{ansible_distribution}}.yml"
      - "{{ansible_os_family}}.yml"
      skip: true

# Setup/install tasks.
- name: Ensure packages are installed
  become: "{{ profile_privilage_escalation }}"
  become_user: "{{ profile_privilage_user }}"
  package: name={{ item }} state=present
  with_items:
    - "{{ profile_package_names }}"

# Ensure /etc/profile.d directory exists
- name: Ensure /etc/profile.d exists
  become: "{{ profile_privilage_escalation }}"
  become_user: "{{ profile_privilage_user }}"
  file: 
    path={{ profile_profiled_path }} 
    state=directory 
    owner={{ profile_owner }} 
    group={{ profile_group }}
    mode=0755

# Copy all profile_profiled_templates to /etc/profile.d
- name: "Copy profile_profiled_templates to {{ profile_profiled_path }}"
  become: "{{ profile_privilage_escalation }}"
  become_user: "{{ profile_privilage_user }}"
  template: 
    src=../templates/profile.d/{{ item }} 
    dest={{ profile_profiled_path }} 
    owner={{ profile_owner }} 
    group={{ profile_group }}
    mode={{ profile_mode }}
  with_items:
    - "{{ profile_profiled_templates }}"

# Copy profile.j2 to {{ profile_profile_path }} if {{ profile_profile_manage }}
- name: "Copy profile template to {{ profile_profile_path }}"
  become: "{{ profile_privilage_escalation }}"
  become_user: "{{ profile_privilage_user }}"
  template: 
    src=../templates/profile.{{ ansible_os_family }}.j2 
    dest={{ profile_profile_path }} 
    owner={{ profile_owner }} 
    group={{ profile_group }}
    mode=0644
  when: "{{ profile_profile_manage }}"

# Copy bashrc.j2 to {{ profile_bashrc_path }} if {{ profile_bashrc_manage }}
- name: "Copy bashrc template to {{ profile_bashrc_path }}"
  become: "{{ profile_privilage_escalation }}"
  become_user: "{{ profile_privilage_user }}"
  template: 
    src=../templates/bashrc.{{ ansible_os_family }}.j2 
    dest={{ profile_bashrc_path }} 
    owner={{ profile_owner }} 
    group={{ profile_group }}
    mode=0644
  when: "{{ profile_bashrc_manage }}"

# Copy environment.j2 to {{ profile_environment_path }} if {{ profile_environment_manage }}
- name: "Copy environment template to {{ profile_environment_path }}"
  become: "{{ profile_privilage_escalation }}"
  become_user: "{{ profile_privilage_user }}"
  template: 
    src=../templates/environment.{{ ansible_os_family }}.j2 
    dest={{ profile_environment_path }} 
    owner={{ profile_owner }} 
    group={{ profile_group }}
    mode=0644
  when: "{{ profile_environment_manage }}"
